# Generated by Django 5.0.6 on 2024-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_application_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
