# Generated by Django 5.0.6 on 2024-05-10 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_alter_applicant_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="gender",
        ),
    ]
